// AUTO-GENERATED by scripts/generate-seeds.mjs. Edit seeds then re-run.
// NMSU Extension publications corpus — metadata + bodies pulled from
// nmsu-content.json at import time.

import content from "./nmsu-content.json";

export interface NmsuDoc {
  id: string;
  pub_number: string;
  title_en: string;
  title_es: string;
  source_url: string;
  content_en: string;
  content_es: string;
  topic_tags: string[];
}

const META = [
  {
    "id": "nmsu-h-230",
    "pub_number": "Guide H-230",
    "title_en": "Chile Production in New Mexico",
    "title_es": "Chile Production in New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H230/",
    "topic_tags": [
      "production",
      "general",
      "planting",
      "cultivars",
      "harvest",
      "spacing"
    ]
  },
  {
    "id": "nmsu-h-219",
    "pub_number": "Guide H-219",
    "title_en": "Curly Top Virus in Chile",
    "title_es": "Curly Top Virus in Chile",
    "source_url": "https://pubs.nmsu.edu/_h/H219/",
    "topic_tags": [
      "disease",
      "virus",
      "curly-top",
      "wilt",
      "yellowing",
      "stunting"
    ]
  },
  {
    "id": "nmsu-h-240",
    "pub_number": "Guide H-240",
    "title_en": "Phytophthora Root Rot of Chile",
    "title_es": "Phytophthora Root Rot of Chile",
    "source_url": "https://pubs.nmsu.edu/_h/H240/",
    "topic_tags": [
      "disease",
      "fungus",
      "phytophthora",
      "wilt",
      "root-rot"
    ]
  },
  {
    "id": "nmsu-a-128",
    "pub_number": "Guide A-128",
    "title_en": "Fertilizing Chile",
    "title_es": "Fertilizing Chile",
    "source_url": "https://pubs.nmsu.edu/_a/A128/",
    "topic_tags": [
      "nutrition",
      "fertilizer",
      "nitrogen",
      "iron",
      "deficiency"
    ]
  },
  {
    "id": "nmsu-h-232",
    "pub_number": "Guide H-232",
    "title_en": "Chile Irrigation",
    "title_es": "Chile Irrigation",
    "source_url": "https://pubs.nmsu.edu/_h/H232/",
    "topic_tags": [
      "irrigation",
      "water",
      "scheduling",
      "drip",
      "surface"
    ]
  },
  {
    "id": "nmsu-h-243",
    "pub_number": "Guide H-243",
    "title_en": "Economic Insects of Chile",
    "title_es": "Economic Insects of Chile",
    "source_url": "https://pubs.nmsu.edu/_h/H243/",
    "topic_tags": [
      "chile",
      "insect",
      "pest",
      "thrips",
      "weevil"
    ]
  },
  {
    "id": "nmsu-h-248",
    "pub_number": "Guide H-248",
    "title_en": "Powdery Mildew on Chile Peppers",
    "title_es": "Powdery Mildew on Chile Peppers",
    "source_url": "https://pubs.nmsu.edu/_h/H248/",
    "topic_tags": [
      "chile",
      "disease",
      "fungus",
      "powdery-mildew"
    ]
  },
  {
    "id": "nmsu-h-249",
    "pub_number": "Guide H-249",
    "title_en": "Chile Pepper Disorders Caused by Environmental Stress",
    "title_es": "Chile Pepper Disorders Caused by Environmental Stress",
    "source_url": "https://pubs.nmsu.edu/_h/H249/",
    "topic_tags": [
      "chile",
      "disorder",
      "heat-stress",
      "wind",
      "salinity",
      "sunscald"
    ]
  },
  {
    "id": "nmsu-h-250",
    "pub_number": "Guide H-250",
    "title_en": "Verticillium Wilt of Chile Peppers",
    "title_es": "Verticillium Wilt of Chile Peppers",
    "source_url": "https://pubs.nmsu.edu/_h/H250/",
    "topic_tags": [
      "chile",
      "disease",
      "verticillium",
      "wilt",
      "soilborne"
    ]
  },
  {
    "id": "nmsu-h-235",
    "pub_number": "Guide H-235",
    "title_en": "Postharvest Handling of Fresh Chiles",
    "title_es": "Postharvest Handling of Fresh Chiles",
    "source_url": "https://pubs.nmsu.edu/_h/H235/",
    "topic_tags": [
      "chile",
      "postharvest",
      "storage",
      "cooling"
    ]
  },
  {
    "id": "nmsu-h-236",
    "pub_number": "Guide H-236",
    "title_en": "Postharvest Handling of Dehydrated Chiles",
    "title_es": "Postharvest Handling of Dehydrated Chiles",
    "source_url": "https://pubs.nmsu.edu/_h/H236/",
    "topic_tags": [
      "chile",
      "postharvest",
      "drying",
      "paprika"
    ]
  },
  {
    "id": "nmsu-h-237",
    "pub_number": "Guide H-237",
    "title_en": "Measuring Chile Pepper Heat",
    "title_es": "Measuring Chile Pepper Heat",
    "source_url": "https://pubs.nmsu.edu/_h/H237/",
    "topic_tags": [
      "chile",
      "pungency",
      "scoville",
      "capsaicin"
    ]
  },
  {
    "id": "nmsu-h-257",
    "pub_number": "Guide H-257",
    "title_en": "Red Chile and Paprika Production in New Mexico",
    "title_es": "Red Chile and Paprika Production in New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H257/",
    "topic_tags": [
      "chile",
      "production",
      "red-chile",
      "paprika"
    ]
  },
  {
    "id": "nmsu-h-258",
    "pub_number": "Guide H-258",
    "title_en": "Field Production of Organic Chile",
    "title_es": "Field Production of Organic Chile",
    "source_url": "https://pubs.nmsu.edu/_h/H258/",
    "topic_tags": [
      "chile",
      "organic",
      "production"
    ]
  },
  {
    "id": "nmsu-h-242",
    "pub_number": "Guide H-242",
    "title_en": "Tomato Spotted Wilt Virus",
    "title_es": "Tomato Spotted Wilt Virus",
    "source_url": "https://pubs.nmsu.edu/_h/H242/",
    "topic_tags": [
      "virus",
      "thrips",
      "disease",
      "tomato",
      "pepper"
    ]
  },
  {
    "id": "nmsu-h-106",
    "pub_number": "Guide H-106",
    "title_en": "Curly Top Virus",
    "title_es": "Curly Top Virus",
    "source_url": "https://pubs.nmsu.edu/_h/H106/",
    "topic_tags": [
      "virus",
      "curly-top",
      "leafhopper",
      "tomato",
      "pepper"
    ]
  },
  {
    "id": "nmsu-a-609",
    "pub_number": "Guide A-609",
    "title_en": "Relay Intercropping Brassicas into Chile and Sweet Corn",
    "title_es": "Relay Intercropping Brassicas into Chile and Sweet Corn",
    "source_url": "https://pubs.nmsu.edu/_a/A609/",
    "topic_tags": [
      "intercropping",
      "brassicas",
      "forage",
      "chile"
    ]
  },
  {
    "id": "nmsu-h-216",
    "pub_number": "Guide H-216",
    "title_en": "When to Harvest Vegetables",
    "title_es": "When to Harvest Vegetables",
    "source_url": "https://pubs.nmsu.edu/_h/H216/",
    "topic_tags": [
      "harvest",
      "vegetables",
      "timing"
    ]
  },
  {
    "id": "nmsu-h-220",
    "pub_number": "Guide H-220",
    "title_en": "Starting Plants Early Outdoors",
    "title_es": "Starting Plants Early Outdoors",
    "source_url": "https://pubs.nmsu.edu/_h/H220/",
    "topic_tags": [
      "season-extension",
      "cold-frame",
      "transplant"
    ]
  },
  {
    "id": "nmsu-h-246",
    "pub_number": "Guide H-246",
    "title_en": "Starting a Community Vegetable Garden",
    "title_es": "Starting a Community Vegetable Garden",
    "source_url": "https://pubs.nmsu.edu/_h/H246/",
    "topic_tags": [
      "community-garden",
      "smallholder",
      "planning"
    ]
  },
  {
    "id": "nmsu-h-251",
    "pub_number": "Guide H-251",
    "title_en": "Row Cover Vegetable Production Techniques",
    "title_es": "Row Cover Vegetable Production Techniques",
    "source_url": "https://pubs.nmsu.edu/_h/H251/",
    "topic_tags": [
      "row-cover",
      "season-extension",
      "frost",
      "pest-exclusion"
    ]
  },
  {
    "id": "nmsu-h-252",
    "pub_number": "Guide H-252",
    "title_en": "Hoop House Vegetable Production",
    "title_es": "Hoop House Vegetable Production",
    "source_url": "https://pubs.nmsu.edu/_h/H252/",
    "topic_tags": [
      "hoop-house",
      "high-tunnel",
      "season-extension"
    ]
  },
  {
    "id": "nmsu-h-261",
    "pub_number": "Guide H-261",
    "title_en": "Mulches for Vegetable Production in New Mexico",
    "title_es": "Mulches for Vegetable Production in New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H261/",
    "topic_tags": [
      "mulch",
      "weed-control",
      "water-conservation"
    ]
  },
  {
    "id": "nmsu-h-262",
    "pub_number": "Guide H-262",
    "title_en": "Vegetable Seed Saving for Home Gardeners and Small-scale Farmers",
    "title_es": "Vegetable Seed Saving for Home Gardeners and Small-scale Farmers",
    "source_url": "https://pubs.nmsu.edu/_h/H262/",
    "topic_tags": [
      "seed-saving",
      "pollination",
      "genetics"
    ]
  },
  {
    "id": "nmsu-h-180",
    "pub_number": "Guide H-180",
    "title_en": "Hydroponics: Water-saving Farming for New Mexico's Arid Environment",
    "title_es": "Hydroponics: Water-saving Farming for New Mexico's Arid Environment",
    "source_url": "https://pubs.nmsu.edu/_h/H180/",
    "topic_tags": [
      "hydroponics",
      "water-saving",
      "greenhouse"
    ]
  },
  {
    "id": "nmsu-h-176",
    "pub_number": "Guide H-176",
    "title_en": "IPM Strategies for Common Garden Insect Pests of New Mexico",
    "title_es": "IPM Strategies for Common Garden Insect Pests of New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H176/",
    "topic_tags": [
      "ipm",
      "pest",
      "vegetable"
    ]
  },
  {
    "id": "nmsu-h-181",
    "pub_number": "Guide H-181",
    "title_en": "IPM for Pollinator Conservation in Home Gardens and Small Farms",
    "title_es": "IPM for Pollinator Conservation in Home Gardens and Small Farms",
    "source_url": "https://pubs.nmsu.edu/_h/H181/",
    "topic_tags": [
      "ipm",
      "pollinator",
      "bee"
    ]
  },
  {
    "id": "nmsu-h-183",
    "pub_number": "Guide H-183",
    "title_en": "IPM for Squash Bug for Home Gardens and Small-scale Growers",
    "title_es": "IPM for Squash Bug for Home Gardens and Small-scale Growers",
    "source_url": "https://pubs.nmsu.edu/_h/H183/",
    "topic_tags": [
      "ipm",
      "squash-bug",
      "cucurbit"
    ]
  },
  {
    "id": "nmsu-h-168",
    "pub_number": "Guide H-168",
    "title_en": "Selection and Use of Insecticides for Organic Production",
    "title_es": "Selection and Use of Insecticides for Organic Production",
    "source_url": "https://pubs.nmsu.edu/_h/H168/",
    "topic_tags": [
      "organic",
      "insecticide",
      "pest"
    ]
  },
  {
    "id": "nmsu-h-169",
    "pub_number": "Guide H-169",
    "title_en": "Using Insectary Plants to Attract and Sustain Beneficial Insects",
    "title_es": "Using Insectary Plants to Attract and Sustain Beneficial Insects",
    "source_url": "https://pubs.nmsu.edu/_h/H169/",
    "topic_tags": [
      "insectary",
      "beneficial-insect",
      "biological-control"
    ]
  },
  {
    "id": "nmsu-h-172",
    "pub_number": "Guide H-172",
    "title_en": "Backyard Beneficial Insects of New Mexico",
    "title_es": "Backyard Beneficial Insects of New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H172/",
    "topic_tags": [
      "beneficial-insect",
      "identification"
    ]
  },
  {
    "id": "nmsu-h-120",
    "pub_number": "Guide H-120",
    "title_en": "Home and Market Garden Fertilization",
    "title_es": "Home and Market Garden Fertilization",
    "source_url": "https://pubs.nmsu.edu/_h/H120/",
    "topic_tags": [
      "fertilizer",
      "nutrient",
      "garden",
      "vegetables"
    ]
  },
  {
    "id": "nmsu-a-114",
    "pub_number": "Guide A-114",
    "title_en": "Test Your Garden Soil",
    "title_es": "Test Your Garden Soil",
    "source_url": "https://pubs.nmsu.edu/_a/A114/",
    "topic_tags": [
      "soil-test",
      "sampling",
      "nutrient"
    ]
  },
  {
    "id": "nmsu-a-147",
    "pub_number": "Guide A-147",
    "title_en": "Agronomic Principles to Help with Farming During Drought Periods",
    "title_es": "Agronomic Principles to Help with Farming During Drought Periods",
    "source_url": "https://pubs.nmsu.edu/_a/A147/",
    "topic_tags": [
      "drought",
      "water-conservation",
      "variety-selection"
    ]
  },
  {
    "id": "nmsu-a-148",
    "pub_number": "Guide A-148",
    "title_en": "Understanding Soil Health for Production Agriculture in New Mexico",
    "title_es": "Understanding Soil Health for Production Agriculture in New Mexico",
    "source_url": "https://pubs.nmsu.edu/_a/A148/",
    "topic_tags": [
      "soil-health",
      "organic-matter",
      "biology"
    ]
  },
  {
    "id": "nmsu-a-150",
    "pub_number": "Guide A-150",
    "title_en": "Principles of Cover Cropping for Arid and Semi-arid Farming Systems",
    "title_es": "Principles of Cover Cropping for Arid and Semi-arid Farming Systems",
    "source_url": "https://pubs.nmsu.edu/_a/A150/",
    "topic_tags": [
      "cover-crop",
      "erosion",
      "soil-health"
    ]
  },
  {
    "id": "nmsu-a-151",
    "pub_number": "Guide A-151",
    "title_en": "Growing Plants in Caliche Soils",
    "title_es": "Growing Plants in Caliche Soils",
    "source_url": "https://pubs.nmsu.edu/_a/A151/",
    "topic_tags": [
      "caliche",
      "soil",
      "alkaline",
      "chlorosis"
    ]
  },
  {
    "id": "nmsu-a-152",
    "pub_number": "Guide A-152",
    "title_en": "Reducing Tillage in Arid and Semi-arid Cropping Systems",
    "title_es": "Reducing Tillage in Arid and Semi-arid Cropping Systems",
    "source_url": "https://pubs.nmsu.edu/_a/A152/",
    "topic_tags": [
      "tillage",
      "conservation",
      "erosion"
    ]
  },
  {
    "id": "nmsu-a-617",
    "pub_number": "Guide A-617",
    "title_en": "Palmer Amaranth Biology and Management",
    "title_es": "Palmer Amaranth Biology and Management",
    "source_url": "https://pubs.nmsu.edu/_a/A617/",
    "topic_tags": [
      "weed",
      "palmer-amaranth",
      "herbicide"
    ]
  },
  {
    "id": "nmsu-h-223",
    "pub_number": "Guide H-223",
    "title_en": "Home and Market Garden Sweet Corn Production",
    "title_es": "Home and Market Garden Sweet Corn Production",
    "source_url": "https://pubs.nmsu.edu/_h/H223/",
    "topic_tags": [
      "sweet-corn",
      "vegetable",
      "garden"
    ]
  },
  {
    "id": "nmsu-h-234",
    "pub_number": "Guide H-234",
    "title_en": "Garlic Production in New Mexico",
    "title_es": "Garlic Production in New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H234/",
    "topic_tags": [
      "garlic",
      "vegetable",
      "production"
    ]
  },
  {
    "id": "nmsu-h-256",
    "pub_number": "Guide H-256",
    "title_en": "NuMex Sweet Onions",
    "title_es": "NuMex Sweet Onions",
    "source_url": "https://pubs.nmsu.edu/_h/H256/",
    "topic_tags": [
      "onion",
      "vegetable",
      "variety"
    ]
  },
  {
    "id": "nmsu-h-221",
    "pub_number": "Guide H-221",
    "title_en": "Spices and Herbs for the Home Garden",
    "title_es": "Spices and Herbs for the Home Garden",
    "source_url": "https://pubs.nmsu.edu/_h/H221/",
    "topic_tags": [
      "herb",
      "spice",
      "garden"
    ]
  },
  {
    "id": "nmsu-h-247",
    "pub_number": "Guide H-247",
    "title_en": "Anthracnose of Cucurbits",
    "title_es": "Anthracnose of Cucurbits",
    "source_url": "https://pubs.nmsu.edu/_h/H247/",
    "topic_tags": [
      "cucurbit",
      "disease",
      "fungal"
    ]
  },
  {
    "id": "nmsu-a-231",
    "pub_number": "Guide A-231",
    "title_en": "Blossom-End Rot",
    "title_es": "Blossom-End Rot",
    "source_url": "https://pubs.nmsu.edu/_a/A231/",
    "topic_tags": [
      "tomato",
      "pepper",
      "disorder",
      "calcium"
    ]
  },
  {
    "id": "nmsu-h-259",
    "pub_number": "Guide H-259",
    "title_en": "Harlequin Bug",
    "title_es": "Harlequin Bug",
    "source_url": "https://pubs.nmsu.edu/_h/H259/",
    "topic_tags": [
      "pest",
      "harlequin-bug",
      "brassica"
    ]
  },
  {
    "id": "nmsu-h-308",
    "pub_number": "Guide H-308",
    "title_en": "Why Fruit Trees Fail to Bear",
    "title_es": "Why Fruit Trees Fail to Bear",
    "source_url": "https://pubs.nmsu.edu/_h/H308/",
    "topic_tags": [
      "fruit-tree",
      "pollination",
      "troubleshooting"
    ]
  },
  {
    "id": "nmsu-h-310",
    "pub_number": "Guide H-310",
    "title_en": "Fruits and Nuts for New Mexico Orchards",
    "title_es": "Fruits and Nuts for New Mexico Orchards",
    "source_url": "https://pubs.nmsu.edu/_h/H310/",
    "topic_tags": [
      "fruit",
      "nut",
      "orchard",
      "variety"
    ]
  },
  {
    "id": "nmsu-h-317",
    "pub_number": "Guide H-317",
    "title_en": "Apple Disease Control",
    "title_es": "Apple Disease Control",
    "source_url": "https://pubs.nmsu.edu/_h/H317/",
    "topic_tags": [
      "apple",
      "disease",
      "orchard"
    ]
  },
  {
    "id": "nmsu-h-327",
    "pub_number": "Guide H-327",
    "title_en": "Pruning the Home Orchard",
    "title_es": "Pruning the Home Orchard",
    "source_url": "https://pubs.nmsu.edu/_h/H327/",
    "topic_tags": [
      "pruning",
      "orchard",
      "fruit"
    ]
  },
  {
    "id": "nmsu-h-324",
    "pub_number": "Guide H-324",
    "title_en": "Home Garden Strawberry Production in New Mexico",
    "title_es": "Home Garden Strawberry Production in New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H324/",
    "topic_tags": [
      "strawberry",
      "small-fruit"
    ]
  },
  {
    "id": "nmsu-h-602",
    "pub_number": "Guide H-602",
    "title_en": "Pecan Orchard Fertilization",
    "title_es": "Pecan Orchard Fertilization",
    "source_url": "https://pubs.nmsu.edu/_h/H602/",
    "topic_tags": [
      "pecan",
      "fertilization",
      "orchard"
    ]
  },
  {
    "id": "nmsu-h-636",
    "pub_number": "Guide H-636",
    "title_en": "Estimating Water Needs for Pecan Trees",
    "title_es": "Estimating Water Needs for Pecan Trees",
    "source_url": "https://pubs.nmsu.edu/_h/H636/",
    "topic_tags": [
      "pecan",
      "irrigation",
      "water"
    ]
  },
  {
    "id": "nmsu-h-657",
    "pub_number": "Guide H-657",
    "title_en": "Diseases and Other Disorders of Pecan in New Mexico",
    "title_es": "Diseases and Other Disorders of Pecan in New Mexico",
    "source_url": "https://pubs.nmsu.edu/_h/H657/",
    "topic_tags": [
      "pecan",
      "disease",
      "disorder"
    ]
  },
  {
    "id": "nmsu-h-110",
    "pub_number": "Guide H-110",
    "title_en": "Backyard Composting",
    "title_es": "Backyard Composting",
    "source_url": "https://pubs.nmsu.edu/_h/H110/",
    "topic_tags": [
      "compost",
      "soil",
      "organic-matter"
    ]
  },
  {
    "id": "nmsu-h-171",
    "pub_number": "Guide H-171",
    "title_en": "Iron Chlorosis",
    "title_es": "Iron Chlorosis",
    "source_url": "https://pubs.nmsu.edu/_h/H171/",
    "topic_tags": [
      "iron",
      "chlorosis",
      "deficiency",
      "alkaline-soil"
    ]
  },
  {
    "id": "nmsu-a-122",
    "pub_number": "Guide A-122",
    "title_en": "Soil Test Interpretations",
    "title_es": "Soil Test Interpretations",
    "source_url": "https://pubs.nmsu.edu/_a/A122/",
    "topic_tags": [
      "soil-test",
      "interpretation",
      "recommendations"
    ]
  },
  {
    "id": "nmsu-cr-573",
    "pub_number": "Circular 573",
    "title_en": "Drip Irrigation for Row Crops",
    "title_es": "Drip Irrigation for Row Crops",
    "source_url": "https://pubs.nmsu.edu/_circulars/CR573/",
    "topic_tags": [
      "irrigation",
      "drip",
      "row-crop"
    ]
  },
  {
    "id": "nmsu-w-102",
    "pub_number": "Guide W-102",
    "title_en": "Irrigation Water Analysis and Interpretation",
    "title_es": "Irrigation Water Analysis and Interpretation",
    "source_url": "https://pubs.nmsu.edu/_w/W102/",
    "topic_tags": [
      "water-quality",
      "salinity",
      "irrigation"
    ]
  },
  {
    "id": "nmsu-cr-477",
    "pub_number": "Circular 477",
    "title_en": "Small Poultry Flock Management",
    "title_es": "Small Poultry Flock Management",
    "source_url": "https://pubs.nmsu.edu/_circulars/CR477/",
    "topic_tags": [
      "poultry",
      "livestock",
      "smallholder"
    ]
  },
  {
    "id": "nmsu-h-149",
    "pub_number": "Guide H-149",
    "title_en": "Marketing Alternatives for Small- to Medium-sized Family Farms and Ranches",
    "title_es": "Marketing Alternatives for Small- to Medium-sized Family Farms and Ranches",
    "source_url": "https://pubs.nmsu.edu/_h/H149/",
    "topic_tags": [
      "marketing",
      "farm-business",
      "direct-sale"
    ]
  },
  {
    "id": "nmsu-cr-701",
    "pub_number": "Circular 701",
    "title_en": "Fruit Tree Freeze and Frost Damage and Its Management",
    "title_es": "Fruit Tree Freeze and Frost Damage and Its Management",
    "source_url": "https://pubs.nmsu.edu/_circulars/CR701/",
    "topic_tags": [
      "frost",
      "freeze",
      "fruit-tree"
    ]
  }
] as const;

const CONTENT = content as Record<string, string>;

export const NMSU_DOCS: NmsuDoc[] = META.map((m) => {
  const body = CONTENT[m.id] ?? "";
  return {
    id: m.id,
    pub_number: m.pub_number,
    title_en: m.title_en,
    title_es: m.title_es,
    source_url: m.source_url,
    content_en: body,
    content_es: body,
    topic_tags: [...m.topic_tags],
  };
});

export function findDoc(id: string): NmsuDoc | undefined {
  return NMSU_DOCS.find((d) => d.id === id);
}
